language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.0
      env: PREFIX="phpdbg -qrr "
    - php: 7.1
      env: PREFIX="phpdbg -qrr "
    - php: nightly
      env: PREFIX="phpdbg -qrr "

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - ${PREFIX} bin/phpspec run

after_success:
  - travis_retry php bin/coveralls
