language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - bin/phpspec run

after_success:
  - travis_retry php bin/coveralls
